Fitness/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('users.urls',namespace='users')),
    path('choice/',include('ly_app.urls',namespace='ly_app')),
    path('command/',include('wly_app.urls',namespace='wly_app')),
    path('device/',include('gsj_app.urls',namespace='gsj_app')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('regist/',views.user_regist,name='user_regist'),
    path('index/',views.user_login,name='user_login'),
]

wly_app/urls.py
from django.urls import path
from . import views

app_name = 'wly_app'

urlpatterns=[
    path('body/', views.body_check, name='body_check'),
    path('test/',views.body_test,name='body_test'),
    path('test/abs/',views.abs_test,name='abs_test'),
    path('test/pecs/',views.pecs_test,name='pecs_test'),
    path("test/limb/",views.limbs_test,name='limb_test'),
    path('test/cox/',views.cox_test,name='cox_test'),
    path('test/heart',views.heart_test,name='heart_test'),
    path('bodyreport',views.body_report,name='body_report'),
    path('warning',views.warning,name='warning'),
    path('trainingplan',views.trainingplan_recommand,name='trainingplan'),
    path('body/bodypic',views.body_pic,name="bodypic"),
    path('warning2',views.warning_two,name='warning2'),

]

wly_app/models.py
from django.db import models
import django.utils.timezone as timezone


class BodyData(models.Model):
    user_name = models.ForeignKey("users.New_User",to_field="login_name",on_delete=models.CASCADE)
    hight = models.DecimalField(max_digits=5,decimal_places=1)
    height = models.DecimalField(max_digits=5,decimal_places=1)
    chest = models.DecimalField(max_digits=5,decimal_places=1)
    waist = models.DecimalField(max_digits=5,decimal_places=1)
    hip = models.DecimalField(max_digits=5,decimal_places=1)
    queith = models.DecimalField(max_digits=5,decimal_places=1)
    maxh = models.DecimalField(max_digits=5,decimal_places=1)
    BMI = models.DecimalField(max_digits=5,decimal_places=1)
    createon = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ["user_name","createon"]

# Create your models here.
class BodyParts(models.Model):
    partcode = models.CharField(max_length=16,primary_key=True)
    partname = models.CharField(max_length=10)

class BodytestStandard(models.Model):
    partcode = models.ForeignKey("BodyParts",to_field="partcode",on_delete=True,related_name="Parts_Test")
    value = models.IntegerField()
    points = models.IntegerField()
    comment = models.CharField(max_length=60,default="c")


    

class UserPysicalTest(models.Model):
    user_name = models.ForeignKey("users.New_User",to_field="login_name",on_delete=models.CASCADE)
    partcode = models.ForeignKey("BodyParts",to_field="partcode",on_delete=models.CASCADE)
    testdata = models.IntegerField()
    createon = models.DateTimeField('创建日期',default=timezone.now)
    testlevel = models.CharField(max_length=30,default="LV0")
    class Meta:
        unique_together = ["user_name","partcode","createon"]

class starlevel(models.Model):
    starcode = models.CharField(max_length=30,primary_key=True)
    stardisplay = models.CharField(max_length=30)



class GradeLevel(models.Model):
    grade = models.IntegerField("成绩",primary_key=True)
    level = models.CharField("等级",max_length=10)

    def __unicode__(self):
        return self.grade

class Courses(models.Model):
    courseid = models.CharField("课程编号",max_length=30,primary_key=True)
    coursename = models.CharField("课程名称",max_length=30)
    decription = models.CharField("课程介绍",max_length=150,default="")
    pic = models.CharField("图片路径",max_length=150,default="./")

    def __unicode__(self):
        return self.courseid

class PartCourse(models.Model):
    partcode = models.ForeignKey("BodyParts",to_field="partcode",on_delete=models.CASCADE)
    courseid = models.ForeignKey("Courses",to_field="courseid",on_delete=models.CASCADE)
    courselevel = models.CharField("课程等级",max_length=10)
    frequency = models.CharField("次数",max_length=30)
    class Meta:
        unique_together = ["partcode","courseid","courselevel"]

    def __unicode__(self):
        return self.partcode,self.courseid

wly_app/views.py
from django.shortcuts import render,redirect
from .form import BodyCheckForm
from .models import BodyData
from .models import BodyParts
from users.models import New_User
from .models import BodytestStandard
from  .models import starlevel
from .models import GradeLevel
from .models import PartCourse
from .models import Courses
from . import models
from  .models import UserPysicalTest
from django.contrib.auth import authenticate, login
from django.http import HttpResponse,JsonResponse
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger,InvalidPage
from datetime import datetime
import matplotlib.pyplot as plt #引入绘图库
from matplotlib.font_manager import FontProperties 

# Create your views here.
from .models import UserPysicalTest

def body_check(request):
    username = request.session.get("user_name")
    user_name = New_User.objects.get(login_name=username)
    if request.method == "POST":
        form = BodyCheckForm(request.POST)
        if form.is_valid():
            hight = form.cleaned_data["hight"]
            heigth = form.cleaned_data["height"]
            chest = form.cleaned_data["chest"]
            waist = form.cleaned_data["waist"]
            hip = form.cleaned_data["hip"]
            queith = form.cleaned_data["queith"]
            maxh = form.cleaned_data["maxh"]
            BMI = round(heigth / ((hight / 100) ** 2), 2)
            bd = BodyData(user_name=user_name, hight=hight, height=heigth, chest=chest, waist=waist, hip=hip,
                              queith=queith, maxh=maxh,BMI = BMI)
            bd.save()
            DrawdataPic(user_name,"BMI","BMI","BMI指数变化图","BMI")
            DrawdataPic(user_name,"weight","weight","体重变化图","体重(kg)")
            DrawdataPic(user_name,"queith","queith","静息心率变化图","静息心率(bpm)")
            DrawdataPic(user_name,"maxh","maxh","最大心率变化图","最大心率(bpm)")
            messages.success(request,"保存成功")
            return render(request, "wly_app/body.html", locals())
        else:
            error_msg =form.errors
            return render(request,"wly_app/body.html",{'form':form,"errors":error_msg})
    try:    
        bd = BodyData.objects.filter(user_name=user_name).order_by("-createon")[0]
        flag = True
        hight = bd.hight
        height = bd.height
        chest = bd.chest
        waist = bd.waist
        hip = bd.hip
        queith = bd.queith
        maxh = bd.maxh
        return render(request, "wly_app/body.html", locals())
    except:
        flag = False

    return render(request,"wly_app/body.html",{'form':BodyCheckForm})

#绘制身体数据变化图
def DrawdataPic(user_name,filename,para,title,yname):
    font_set = FontProperties(fname=r"./static/font/MSYH.TTC") 
    datarecord = BodyData.objects.filter(user_name=user_name).order_by("createon")
    data=[]
    time=[]           
    if para=="BMI":
        for record in datarecord:
            data.append(record.BMI)
            time.append(record.createon)
    elif para=="weight":
        for record in datarecord:
            data.append(record.height)
            time.append(record.createon)
    elif para=="queith":
        for record in datarecord:
            data.append(record.queith)
            time.append(record.createon)  
    else:
        for record in datarecord:
            data.append(record.maxh)
            time.append(record.createon)       
    xs = [datetime.strptime(str(d)[0:10],"%Y-%m-%d").date() for d in time]
    plt.figure(dpi=80)
    plt.title(title,fontproperties=font_set,fontsize=17)
    plt.plot(xs,data,'o-')
    plt.xlabel("测试日期",fontproperties=font_set,fontsize=12)
    plt.gcf().autofmt_xdate()
    plt.ylabel(yname,fontproperties=font_set,fontsize=12)
    plt.savefig("./static/img/"+filename+".png")    

def body_pic(request):
    try:
        username = request.session.get("user_name")
        user_name = New_User.objects.get(login_name=username)
        bd = BodyData.objects.filter(user_name=user_name).order_by("-createon")[0]
        BMIfr = "/static/img/BMI.png"
        Wefr = "/static/img/weight.png"
        Queifr = "/static/img/queith.png"
        Maxfr = "/static/img/maxh.png"
    except:
        return redirect("/command/warning2")
    return render(request,"wly_app/bodypic.html",locals())
#体能测试页面
def body_test(request):
    username = request.session.get("user_name")
    user_name = New_User.objects.get(login_name = username)
    bd_finish = False
    abs_finish = False
    pec_finish = False
    cox_finish = False
    limb_finish = False
    ht_finish = False
    try:
        bd_data = BodyData.objects.filter(user_name=user_name)[0]
        bd_finish = True
        hight = bd_data.hight
        height = bd_data.height
        BMI = bd_data.BMI
    except:
        pass
    try:
        partcode = BodyParts.objects.get(partname="腹肌")
        abstest = UserPysicalTest.objects.filter(user_name = user_name,partcode=partcode).count()
        if abstest !=0:
            abs_finish = True
    except:
        pass
    try:
        partcode = BodyParts.objects.get(partname="胸肌")
        pectest = UserPysicalTest.objects.filter(user_name=user_name, partcode=partcode).count()
        if pectest != 0 :
            pec_finish = True
    except:
        pass
    try:
        partcode = BodyParts.objects.get(partname="下肢")
        limbtest = UserPysicalTest.objects.filter(user_name=user_name, partcode=partcode).count()
        if limbtest !=0:
            limb_finish = True
    except:
        pass
    try:
        partcode = BodyParts.objects.get(partname="髋关节")
        coxtest = UserPysicalTest.objects.filter(user_name=user_name, partcode=partcode).count()
        if coxtest !=0:
            cox_finish = True
    except:
        pass
    try:
        partcode = BodyParts.objects.get(partname="心肺")
        hearttest = UserPysicalTest.objects.filter(user_name=user_name, partcode=partcode).count()
        if hearttest !=0:
            ht_finish = True
    except:
        pass
    return render(request,"wly_app/physicaltest.html",locals())

# 腹肌能力测试
def abs_test(request):
    username = request.session.get("user_name")
    if request.method == "POST":
        part_test(request,"腹肌",username,"abs")
        return redirect("/command/test")
    return render(request,"wly_app/abstest.html",locals())

#胸肌能力测试
def pecs_test(request):
    username = request.session.get("user_name")
    if request.method == "POST":
        part_test(request,"胸肌",username,"pec")
        return redirect("/command/test")
    return render(request,"wly_app/pecstest.html",locals())

#下肢能力测试
def limbs_test(request):
    username = request.session.get("user_name")
    if request.method == "POST":
        part_test(request,"下肢",username,"limb")
        return redirect("/command/test")
    return render(request,"wly_app/limbtest.html")

#髋关节能力测试
def cox_test(request):
    username = request.session.get("user_name")
    if request.method == "POST":
        part_test(request,"髋关节",username,"cox")
        return redirect("/command/test")
    return render(request,'wly_app/coxtest.html')

#心肺能力测试
def heart_test(request):
    username = request.session.get("user_name")
    if request.method == "POST":
        part_test(request,"心肺",username,"heart")
        return redirect("/command/test")
    return  render(request,'wly_app/heart.html')

#完成用户的体能测试
def part_test(request,partname,username,paraname):
    user_name = New_User.objects.get(login_name=username)
    testdata = request.POST.get(paraname)
    partcode  = BodyParts.objects.get(partname=partname)
    if partname=="心肺":
        partgrade = GetHeartGrade(partname,testdata)
    else:
        partgrade = GetGrade(partname,testdata)
    partlevel = Getlevel(partgrade)
    # 形成用户的测试数据
    parttest = UserPysicalTest(user_name=user_name, partcode=partcode, testdata=testdata,testlevel=partlevel)
    parttest.save()
    messages.success(request, "测试成功！")


#获取体能力信息
def GetTestInfo(user_name,partname):
    partcode = BodyParts.objects.get(partname=partname)
    partdata = UserPysicalTest.objects.filter(user_name=user_name,partcode=partcode).order_by("-createon")[0].testdata
    cpcomment = TestCompareComment(user_name,partcode)
    if partname=="心肺":
        partgrade = GetHeartGrade(partname,partdata)
        partcomment = GetHeartComment(user_name)
    else:
        partgrade = GetGrade(partname,partdata)
        partcomment = GetComment(user_name,partname)
    partstar = StarShow(partgrade)
    return partgrade,partstar,partcomment,cpcomment

#用户的体测报告
def body_report(request):
    username = request.session.get("user_name")
    # 获取腹肌肌耐力的评分
    user_name = New_User.objects.get(login_name=username)
    try:
        absgrade,absstar,abscomment,abscpcomment = GetTestInfo(username,"腹肌")
        pecgrade,pecstar,peccomment,peccpcomment = GetTestInfo(username,"胸肌")
        limbgrade,limbstar,limbcomment,limbcpcomment = GetTestInfo(username,"下肢")
        coxgrade,coxstar,coxcomment,coxcpcomment = GetTestInfo(username,"髋关节")
        htgrade,heartstar,htcomment,htcpcomment = GetTestInfo(username,"心肺")
        score = ScoreCalculate(absgrade,pecgrade,limbgrade,coxgrade,htgrade)       
        return render(request,'wly_app/bodyreport.html',locals())
    except:
        return redirect("/command/warning")
    return render(request,'wly_app/bodyreport.html',locals())

#获取能力评分
def GetGrade(partname,testdata):
    #拿到用户的能力测试数据
    partcode = BodyParts.objects.get(partname=partname)
    testnum = testdata
    testgrade = BodytestStandard.objects.filter(value__lte=testnum,partcode=partcode).order_by("-points")[0].points
    return testgrade

#获取能力评价
def GetComment(username,partname):
    user_name = New_User.objects.get(login_name=username)
    #拿到用户的能力测试数据
    partcode = BodyParts.objects.get(partname=partname)
    testnum = UserPysicalTest.objects.filter(user_name=user_name,partcode=partcode).order_by("-createon")[0].testdata

templates/wly_app/abstest.html
{% load staticfiles %}
<meta http-equiv='Content-type' content='text/htm'>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/page3.css' %}" />

    <title>腹肌能力测试</title>
</head>
<body bgcolor="" >
            <input type="button" value="返回" class="button" onclick="location.href='/command/test'">
    <form method="post" class="basic-grey">
        {% csrf_token %}
        <center> <H1>腹肌能力测试</H1> </center>
        <b>测试前请先观看以下视频</b><br><br>
<iframe class="ifvideo" src="//player.bilibili.com/player.html?aid=34252946&cid=60001401&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>
<!----><H1></H1>
        <span><b>一分钟内：完成的卷腹数量是</b></span>
        <input type="number" name="abs"  style="width: 70px">次<!----> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <input type="submit" value="确定" class="button">
        <br>
        <br>
        <br>


    </form>


</body>
</html>

templates/wly_app/addcourse.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <title>推荐课程信息管理</title>
</head>
<body bgcolor="#F7F7F7">
    <div class="container my-con">
        <H3>添加推荐课程</H3>
    <form action="" method="post">
        {% csrf_token %}
        

            <div class="col-md-10">
        <div class="form-group">
            <label for="courseid" style="margin-left: 200px;margin-top: 50px;">课程编号</label>
            <input type="text" class="form-control" id="courseid" name="courseid" style="width: 200px; margin-left: 200px;">
        </div>

        <div class="form-group">
            <label for="coursename"" style="margin-left: 200px;">课程名称</label>
            <input type="text" class="form-control" id="coursename" name="coursename" style="width: 200px;margin-left: 200px;">
        </div>

        <div class="form-group">
            <label for="description" style="margin-left: 200px;">课程描述</label>
            <textarea  class="form-control" id="description" name="description" style="height: 100px;;width: 400px;margin-left: 200px;"></textarea>
        </div>

        
        <a href="/command/coursemanage"><button type="button"  class="btn btn-success pull-right" style="margin-left: 10px;">返回</button></a>
        &nbsp;&nbsp;<button type="submit" class="btn btn-success pull-right">提交</button>
    </div>
    </div>
    </form>



</body>
</html>

templates/wly_app/addtest.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <title>能力测试信息管理</title>
</head>
<body bgcolor="#F7F7F7">
    <div class="container my-con">
        <H3>添加能力测试</H3>
    <form action="" method="post">
        {% csrf_token %}
        

            <div class="col-md-10">
        <div class="form-group">
            <label for="partcode" style="margin-left: 200px;margin-top: 50px;">测试编号</label>
            <input type="text" class="form-control" id="partcode" name="partcode" style="width: 200px; margin-left: 200px;">
        </div>

        <div class="form-group">
            <label for="partname" style="margin-left: 200px;">测试部位名称</label>
            <input type="text" class="form-control" id="partname" name="partname" style="width: 200px;margin-left: 200px;">
        </div>

        <div class="form-group">
            <label for="testname" style="margin-left: 200px;">能力测试名称</label>
            <input type="text" class="form-control" id="testname" name="testname" style="width: 200px;margin-left: 200px;">
        </div>

        <div class="form-group">
            <label for="description" style="margin-left: 200px;">能力测试介绍</label>
            <input type="text" class="form-control" id="description" name="description" style="width: 500px;margin-left: 200px;">
        </div>
        <a href="/command/pytestmanage"><button type="button"  class="btn btn-success pull-right" style="margin-left: 10px;">返回</button></a>
        &nbsp;&nbsp;<button type="submit" class="btn btn-success pull-right">提交</button>
    </div>
    </div>
    </form>



</body>
</html>

templates/wly_app/body.html
{% load staticfiles %}
<meta http-equiv='Content-type' content='text/htm'>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/page2.css' %}" />

    <title>我的身体数据</title>
</head>
<body bgcolor="#F7F7F7">
<form method="post" action="/command/body/" class="basic-grey">
{% csrf_token %}
    <H1>我的身体数据</H1>
    <span>身高(cm)：</span>
    <div class="inputbox">
        {% if flag %}
        <input type="number" name="hight" value={{hight}} step="any" required id="id_hight">
        {% else %}
        {{ form.hight}}
        {% endif %}
    </div>
    {{ errors.hight}}
    <br>
    <span>体重(kg)：</span>
     <div class="inputbox">
          {% if flag %}
         <input type="number" name="height" value={{height}} step="any" required id="id_height">
         {% else %}
        {{ form.height}}
        {% endif %}
     </div>
    {{ errors.height}}
    <br>
    <span>胸围(cm)：</span>
    <div class="inputbox">
    {% if flag %}
         <input type="number" name="chest" value={{chest}} step="any" required id="id_chest">
         {% else %}
        {{ form.chest}}
        {% endif %}
    </div>
    <span>{{ errors.chest}}</span><br>
    <span>腰围(cm)：</span>
    <div class="inputbox">
   {% if flag %}
         <input type="number" name="waist" value={{waist}} step="any" required id="id_waist">
         {% else %}
        {{ form.waist}}
        {% endif %}
    </div>
{{ errors.waist}}

    <span>臀围(cm)：</span>
    <div class="inputbox">
     {% if flag %}
         <input type="number" name="hip" value={{hip}} step="any" required id="id_hip">
         {% else %}
        {{ form.hip}}
        {% endif %}
    </div>
<span>{{ errors.hip}}</span>
    <H1></H1>
    <span>静息心率(bpm)：</span>
    <div class="inputbox">
      {% if flag %}
         <input type="number" name="queith" value={{queith}} step="any" required id="id_queith">
         {% else %}
        {{ form.queith}}
        {% endif %}
    </div>
    {{ errors.queith}}
        <br><br>

    <span>最大心率(bpm)：</span>
    <div class="inputbox">
    {% if flag %}
         <input type="number" name="maxh" value={{maxh}} step="any" required id="id_maxh">
         {% else %}
        {{ form.maxh}}
        {% endif %}

    </div>
     {{ errors.maxh}}
    <br><br>
    <input value="保存" type="submit" style="background: #295088;
    border: none;
    padding: 10px 25px 10px 25px;
    color: #FFF;
    box-shadow: 1px 1px 5px #B6B6B6;
    border-radius: 3px;
    text-shadow: 1px 1px 1px #9E3F3F;
    cursor: pointer;
    margin-left: 370px;
    margin-right: 100px;" >
</form>
    <!-- <center><input type="submit" value="保存" class="button">  -->
    <button onclick="javascript:window.location.href='/command/body/bodypic'" style="background: #295088;
        border: none;
        padding: 10px 25px 10px 25px;
        color: #FFF;
        box-shadow: 1px 1px 5px #B6B6B6;
        border-radius: 3px;
        text-shadow: 1px 1px 1px #9E3F3F;
        cursor: pointer;
        margin-left: 370px;
        " >查看数据监测</button>

{% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}




</body>
</html>

templates/wly_app/bodypic.html
{% load staticfiles %}
<meta http-equiv='Content-type' content='text/htm'>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/page2.css' %}" />
    <title>身体数据动态监测</title>
</head>
<body bgcolor="#F7F7F7">
<!-- Table goes in the document BODY -->
<table class="gridtable" style="margin-left:25%;width: 550px;">
<tr>
    <th>身体数据动态监测</th>
</tr>

<tr>
	<td>
        <img src="{{BMIfr}}" style="">
        </br>️
    </td>
</tr>
    <tr>
	<td>
        <img src="{{Wefr}}" style="">

        </br>️
    </td>
</tr>
<tr>
	<td>
        <img src="{{Queifr}}" style="">

        </br>️
    </td>
</tr>
<tr>
	<td>
        <img src="{{Maxfr}}" style="">

        </br>️
    </td>
</tr>
</table>
</body>
</html>

templates/wly_app/bodyreport.html
{% load staticfiles %}
<meta http-equiv='Content-type' content='text/htm'>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/page2.css' %}" />
    <title>体测报告</title>
</head>
<body bgcolor="#F7F7F7">
<!-- Table goes in the document BODY -->
<table class="gridtable" style="margin-left:25%;width: 550px;">
<tr>
    <th>体测报告</th>
</tr>
<tr>
    <td><b>体测得分：</b> {{score}}分 <br>
    </td>
    </tr>
    <tr>
    <th>各项能力</th>
</tr>
<tr>
	<td>
        <b>胸肌肌耐力：</b>&nbsp;{{pecstar}}&nbsp;&nbsp;{{peccpcomment}}<br><br>
{{peccomment}}
        </br>️
    </td>
</tr>
    <tr>
	<td>
        <b>腹部肌耐力：</b></a> &nbsp;&nbsp;&nbsp;{{ absstar }}&nbsp;&nbsp;{{abscpcomment}}<br><br>
        {{abscomment}}
        </br>️
    </td>
</tr>
     <tr>
	<td>
        <b>下肢肌耐力：</b> &nbsp;&nbsp;&nbsp;{{limbstar}}&nbsp;&nbsp;{{limbcpcomment}}<br><br>
        {{limbcomment}}
         </br>️
    </td>
</tr>
    <tr>
	<td>
        <b>髋关节活动度：</b> {{coxstar}}&nbsp;&nbsp;{{coxcpcomment}}<br><br>
        {{coxcomment}}
         </br>️
    </td>
</tr>
        <tr>
	<td>
        <b>心肺能力：</b>&nbsp;{{heartstar}}&nbsp;&nbsp;{{htcpcomment}}<br><br>
        {{htcomment}}
         </br>️
    </td>
</tr>
<tr>
	<td>
<a href="/command/trainingplan"><button style="background: #295088;
	border: none;
	padding: 10px 25px 10px 25px;
	color: #FFF;
	box-shadow: 1px 1px 5px #B6B6B6;
	border-radius: 3px;
	text-shadow: 1px 1px 1px #9E3F3F;
    cursor: pointer;
    margin-left: 200px;" >获取推荐训练</button></a>
</td>

</tr>
</table>
{% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
</body>
</html>

templates/wly_app/coxtest.html
{% load staticfiles %}
<meta http-equiv='Content-type' content='text/htm'>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>髋关节柔韧性测试</title>
    <link rel="stylesheet" href="{% static 'css/page3.css' %}" />
</head>
<body bgcolor="" >
        <input type="button" value="返回" class="button" onclick="location.href='/command/test'">
    <form method="post" class="basic-grey">
                        {% csrf_token %}
         <H1>髋关节柔韧性测试</H1>
        测试前请先观看以下视频<br><br>
<iframe class="ifvideo" src="//player.bilibili.com/player.html?aid=46655848&cid=81730546&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe><!----><H1></H1>
        <span>在最好的情况下，双腿与地面的夹角是？</span>
        <input type="number" name="cox" style="width: 70px;">度 &nbsp;&nbsp;&nbsp;
        <input type="submit" value="确定" class="button" >
        <br>
        <br>

    </form>
</body>
</html>

templates/wly_app/heart.html
{% load staticfiles %}
<meta http-equiv='Content-type' content='text/htm'>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>心肺功能测试</title>
    <link rel="stylesheet" href="{% static 'css/page3.css' %}" />
</head>
<body bgcolor="">
        <input type="button" value="返回" class="button" onclick="location.href='/command/test'">
    <form method="post" class="basic-grey">
                        {% csrf_token %}
         <H1>心肺功能测试</H1>
        请如图所示完成动作<br><br>
        <img src="{% static 'img/heart.jpg' %}" style="width: 500px;height: 400px;"><br><br>
        <span>10秒内的脉搏数量是？</span>
        <input type="number" name="heart"  style="width: 70px">次<!----> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <input type="submit" value="确定" class="button">
        <br>

    </form>
</body>
</html>

templates/wly_app/warning.html
{% load staticfiles %}
<meta http-equiv='Content-type' content='text/htm'>
<html lang="en" style="text-align: center;">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/page3.css' %}" />
    <style>
    </style>
    <title>体测报告</title>
</head>
<body>
    <div style="margin: 25%;">
           <h1>请先完善体能测试</h1>
            <a href="/command/test/"><button class="button" >开始体能测试</button></a>
        </div>
</body>

</html>